#pragma once

#include <string>
#include <string_view>
#include <vector>
#include <fstream>
#include <iostream>
#include <limits>
#include <functional>
#include <filesystem>
#include <chrono>
#include <exception>
#include <memory>
#include <utility>
#include <unordered_map>
#include <semaphore>
#include "imgui/imgui.h"
#include "imgui/imgui_stdlib.h"
#include "imgui/implot.h"
#include "Log.h"
#include "Settings.h"